import { Text } from 'react-native';
import { useTheme } from '../../theme';

export function AILabel() {
  const { colors } = useTheme();
  return (
    <Text
      style={{
        fontSize: 12,
        color: colors['text-tertiary'],
        fontFamily: 'Inter_400Regular',
        letterSpacing: 0.3,
      }}
      accessibilityLabel="Generated by AI"
    >
      Generated by AI
    </Text>
  );
}
